name: Build and test Go
on:
  - push
  - pull_request:
      types: [opened, sychronize, reopened, review_requested, ready_for_review]
jobs:
  build:
    name: Build
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Set-up Go 1.15.1
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.1
      - name: Check out source code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint
      - name: Run build
        run: go build -a ./...
      - name: Run vet and lint
        run: |
          go vet ./...
          golint ./...
      - name: Run tests
        run: go test -v ./...
